spring:
  application:
    name: user-thrift-server
  datasource:
    url: jdbc:mysql://192.168.92.103:3306/db_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 694975
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 7911