server:
  port: 8082

spring:
  application:
    name: user-edge-service
  redis:
    host: 192.168.92.102
    port: 6379
    timeout: 30000

thrift:
  user:
    ip: 127.0.0.1
    port: 7911
  message:
    ip: 127.0.0.1
    port: 9090